# -*- coding: utf-8 -*-

{
    'name': 'Logistic Management',
    'version': '1.0.0',
    'category': 'Logistic',
    'author': 'Volkan',
    'sequence': -110,
    'summary': 'Logistic management system',
    'description': "Logistic management system controller",
    'depends': [
        'mail',
        'hr',
        'account',
        'fleet',
        'product',
        'hr_contract',
        'stock',
        'mrp',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/hr_data.xml',
        'data/customs_data.xml',
        'report/report_cmr_templates.xml',
        'report/report_declaration_templates.xml',
        'report/report_miscellaneous_templates.xml',
        'views/cargo_information_view.xml',
        'views/customs_view.xml',
        'views/hr_employee_views.xml',
        'views/fleet_vehicle_view.xml',
        'views/trailer_view.xml',
        'views/menu.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'assets': {},
    'license': 'LGPL-3'
}
